console.log("Look I'm Logging from the console");
var givenName;
console.log(givenName);
var greeting = "hello, how are you";
var givenName=" Brett ?";
console.log(greeting+givenName);
var high = 50;
var low  = 10;
var math = high - low;
console.log(high-low);
var born = 1966;
var today = 2017;
var age=today-born;
console.log(age);
var name='Erik' ;
console.log(name+" is "+age+" years old");
var yourName='Erik';
var instructorName='Tori';
var statement = yourName + " is taking a class at The Iron Yard, my instructor's name is " + instructorName;
console.log(statement);
